package Modelo;
// Generated 10-27-2014 07:00:47 PM by Hibernate Tools 3.6.0




/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idproducto;
     private Categoria categoria;
     private String nombre;
     private String descripcion;

    public Producto() {
    }

    public Producto(int idproducto, Categoria categoria, String nombre, String descripcion) {
       this.idproducto = idproducto;
       this.categoria = categoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }

    public Producto(Categoria categoria, String nombre, String descripcion) {
        this.categoria = categoria;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    
    public Categoria getCategoria() {
        return this.categoria;
    }
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    
    public String getNombre() {
        return this.nombre;
    }
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public String getDescripcion() {
        return this.descripcion;
    }
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    public boolean esIgual(String nombre){
        return nombre == this.nombre;
    }
}


